import { z } from "zod";

import { parseEnv } from "@/core/config/env-validation";

const publicEnvsSchema = z.object({
  NEXT_PUBLIC_BASE_URL_APP: z.string().url(),
  NEXT_PUBLIC_APP_NAME: z.string().min(1),
  NEXT_PUBLIC_SIDEBAR_TITLE: z.string().min(1),
  NEXT_PUBLIC_APP_URL: z.string().url(),
  NEXT_PUBLIC_DEVELOPER_NAME: z.string().min(1),
  NEXT_PUBLIC_DEVELOPER_URL: z.string().url(),
  NEXT_PUBLIC_COMPANY_NAME: z.string().min(1),
  NEXT_PUBLIC_COMPANY_LEGAL_NAME: z.string().min(1),
  NEXT_PUBLIC_COMPANY_ABOUT: z.string().min(1),
  NEXT_PUBLIC_COMPANY_INVITATION: z.string().min(1),
  NEXT_PUBLIC_COMPANY_YEAR_FOUNDATION: z.coerce.number().int().positive(),
  NEXT_PUBLIC_COMPANY_QT_PRODUCTS: z.coerce.number().int().nonnegative(),
  NEXT_PUBLIC_COMPANY_CNPJ: z.string().min(1),
  NEXT_PUBLIC_COMPANY_ADDRESS: z.string().min(1),
  NEXT_PUBLIC_COMPANY_ADDRESS_LOCATION: z.string().min(1),
  NEXT_PUBLIC_COMPANY_ADDRESS_CEP: z.string().min(8).max(9),
  NEXT_PUBLIC_COMPANY_ADDRESS_LATITUDE: z.coerce.number().min(-90).max(90),
  NEXT_PUBLIC_COMPANY_ADDRESS_LONGITUDE: z.coerce.number().min(-180).max(180),
  NEXT_PUBLIC_COMPANY_PHONE: z.string().min(10).max(20),
  NEXT_PUBLIC_COMPANY_EMAIL: z.string().email(),
  NEXT_PUBLIC_COMPANY_WHATSAPP: z.string().min(10).max(20),
  NEXT_PUBLIC_COMPANY_WHATSAPP_URL: z.string().url(),
  NEXT_PUBLIC_COMPANY_FACEBOOK_URL: z.string().url(),
  NEXT_PUBLIC_COMPANY_INSTAGRAM_URL: z.string().url(),
  NEXT_PUBLIC_COMPANY_LINKTREE_URL: z.string().url(),
  NEXT_PUBLIC_COMPANY_MAPS_URL: z.string().url(),
  NEXT_PUBLIC_COMPANY_GOOGLE_BUSINESS_URL: z.string().url(),
  NEXT_PUBLIC_COMPANY_OPENING_HOURS: z.string().min(1),
  NEXT_PUBLIC_COMPANY_OPENING_SATURDAY: z.string().min(1),
  NEXT_PUBLIC_COMPANY_META_TITLE_MAIN: z
    .string()
    .min(1, "NEXT_PUBLIC_COMPANY_META_TITLE_MAIN is required"),
  NEXT_PUBLIC_COMPANY_META_TITLE_CAPTION: z
    .string()
    .min(1, "NEXT_PUBLIC_COMPANY_META_TITLE_CAPTION is required"),
  NEXT_PUBLIC_COMPANY_META_TITLE: z
    .string()
    .min(1, "NEXT_PUBLIC_COMPANY_META_TITLE is required"),
  NEXT_PUBLIC_COMPANY_META_DESCRIPTION: z
    .string()
    .min(1, "NEXT_PUBLIC_COMPANY_META_DESCRIPTION is required"),
  NEXT_PUBLIC_COMPANY_META_KEYWORDS: z
    .string()
    .min(1, "NEXT_PUBLIC_COMPANY_META_KEYWORDS is required"),

  NEXT_PUBLIC_DISCOUNT_CASH_PAYMENT: z.coerce.number().nonnegative(),
  NEXT_PUBLIC_PAY_IN_UP_TO: z.coerce.number().int().positive(),
  NEXT_PUBLIC_FREE_SHIPPING_OVER: z.coerce.number().nonnegative(),
  NEXT_PUBLIC_GA_MEASUREMENT_ID: z.string().min(1),
});

export const publicEnvs = parseEnv(
  publicEnvsSchema,
  {
    NEXT_PUBLIC_BASE_URL_APP: process.env.NEXT_PUBLIC_BASE_URL_APP,
    NEXT_PUBLIC_APP_NAME: process.env.NEXT_PUBLIC_APP_NAME,
    NEXT_PUBLIC_SIDEBAR_TITLE: process.env.NEXT_PUBLIC_SIDEBAR_TITLE,
    NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
    NEXT_PUBLIC_DEVELOPER_NAME: process.env.NEXT_PUBLIC_DEVELOPER_NAME,
    NEXT_PUBLIC_DEVELOPER_URL: process.env.NEXT_PUBLIC_DEVELOPER_URL,
    NEXT_PUBLIC_COMPANY_NAME: process.env.NEXT_PUBLIC_COMPANY_NAME,
    NEXT_PUBLIC_COMPANY_LEGAL_NAME: process.env.NEXT_PUBLIC_COMPANY_LEGAL_NAME,
    NEXT_PUBLIC_COMPANY_ABOUT: process.env.NEXT_PUBLIC_COMPANY_ABOUT,
    NEXT_PUBLIC_COMPANY_INVITATION: process.env.NEXT_PUBLIC_COMPANY_INVITATION,
    NEXT_PUBLIC_COMPANY_YEAR_FOUNDATION:
      process.env.NEXT_PUBLIC_COMPANY_YEAR_FOUNDATION,
    NEXT_PUBLIC_COMPANY_QT_PRODUCTS:
      process.env.NEXT_PUBLIC_COMPANY_QT_PRODUCTS,
    NEXT_PUBLIC_COMPANY_CNPJ: process.env.NEXT_PUBLIC_COMPANY_CNPJ,
    NEXT_PUBLIC_COMPANY_ADDRESS: process.env.NEXT_PUBLIC_COMPANY_ADDRESS,
    NEXT_PUBLIC_COMPANY_ADDRESS_LOCATION:
      process.env.NEXT_PUBLIC_COMPANY_ADDRESS_LOCATION,
    NEXT_PUBLIC_COMPANY_ADDRESS_CEP:
      process.env.NEXT_PUBLIC_COMPANY_ADDRESS_CEP,
    NEXT_PUBLIC_COMPANY_ADDRESS_LATITUDE:
      process.env.NEXT_PUBLIC_COMPANY_ADDRESS_LATITUDE,
    NEXT_PUBLIC_COMPANY_ADDRESS_LONGITUDE:
      process.env.NEXT_PUBLIC_COMPANY_ADDRESS_LONGITUDE,
    NEXT_PUBLIC_COMPANY_PHONE: process.env.NEXT_PUBLIC_COMPANY_PHONE,
    NEXT_PUBLIC_COMPANY_EMAIL: process.env.NEXT_PUBLIC_COMPANY_EMAIL,
    NEXT_PUBLIC_COMPANY_WHATSAPP: process.env.NEXT_PUBLIC_COMPANY_WHATSAPP,
    NEXT_PUBLIC_COMPANY_WHATSAPP_URL:
      process.env.NEXT_PUBLIC_COMPANY_WHATSAPP_URL,
    NEXT_PUBLIC_COMPANY_FACEBOOK_URL:
      process.env.NEXT_PUBLIC_COMPANY_FACEBOOK_URL,
    NEXT_PUBLIC_COMPANY_INSTAGRAM_URL:
      process.env.NEXT_PUBLIC_COMPANY_INSTAGRAM_URL,
    NEXT_PUBLIC_COMPANY_LINKTREE_URL:
      process.env.NEXT_PUBLIC_COMPANY_LINKTREE_URL,
    NEXT_PUBLIC_COMPANY_MAPS_URL: process.env.NEXT_PUBLIC_COMPANY_MAPS_URL,
    NEXT_PUBLIC_COMPANY_GOOGLE_BUSINESS_URL:
      process.env.NEXT_PUBLIC_COMPANY_GOOGLE_BUSINESS_URL,
    NEXT_PUBLIC_COMPANY_OPENING_HOURS:
      process.env.NEXT_PUBLIC_COMPANY_OPENING_HOURS,
    NEXT_PUBLIC_COMPANY_OPENING_SATURDAY:
      process.env.NEXT_PUBLIC_COMPANY_OPENING_SATURDAY,
    NEXT_PUBLIC_COMPANY_META_TITLE_MAIN:
      process.env.NEXT_PUBLIC_COMPANY_META_TITLE_MAIN,
    NEXT_PUBLIC_COMPANY_META_TITLE_CAPTION:
      process.env.NEXT_PUBLIC_COMPANY_META_TITLE_CAPTION,
    NEXT_PUBLIC_COMPANY_META_TITLE: process.env.NEXT_PUBLIC_COMPANY_META_TITLE,
    NEXT_PUBLIC_COMPANY_META_DESCRIPTION:
      process.env.NEXT_PUBLIC_COMPANY_META_DESCRIPTION,
    NEXT_PUBLIC_COMPANY_META_KEYWORDS:
      process.env.NEXT_PUBLIC_COMPANY_META_KEYWORDS,
    NEXT_PUBLIC_DISCOUNT_CASH_PAYMENT:
      process.env.NEXT_PUBLIC_DISCOUNT_CASH_PAYMENT,
    NEXT_PUBLIC_PAY_IN_UP_TO: process.env.NEXT_PUBLIC_PAY_IN_UP_TO,
    NEXT_PUBLIC_FREE_SHIPPING_OVER: process.env.NEXT_PUBLIC_FREE_SHIPPING_OVER,
    NEXT_PUBLIC_GA_MEASUREMENT_ID: process.env.NEXT_PUBLIC_GA_MEASUREMENT_ID,
  },
  {
    scope: "client",
    sourceFiles: [".env", ".env.local"],
  },
);

export type PublicEnvs = z.infer<typeof publicEnvsSchema>;
